name: Discord Notification on Release

on:
  release:
    types: [created, edited, deleted]

jobs:
  pre_release_created:
    if: github.event.release.prerelease == true && github.event.action == 'created'
    runs-on: ubuntu-latest
    steps:
      - name: Pre-release Created Message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            A new pre-release version of ${{ github.repository }} has been created!

            **Release Description:**
            ```
            ${{ github.event.release.body }}
            ```

            Check it out at: ${{ github.event.release.html_url }}

  new_release_created:
    if: github.event.release.prerelease == false && github.event.action == 'created'
    runs-on: ubuntu-latest
    steps:
      - name: New Release Created Message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            A new Release version of ${{ github.repository }} has been created!

            **Release Description:**
            ```
            ${{ github.event.release.body }}
            ```

            Check it out at: ${{ github.event.release.html_url }}

  pre_release_changed:
    if: github.event.release.prerelease == true && github.event.action == 'edited' && contains(github.event.changes, 'prerelease')
    runs-on: ubuntu-latest
    steps:
      - name: Pre-Release Changed Message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            Pre-release version of ${{ github.repository }} has been changed to a Release!

            **Release Description:**
            ```
            ${{ github.event.release.body }}
            ```

            Check it out at: ${{ github.event.release.html_url }}

  release_deleted:
    if: github.event.action == 'deleted'
    runs-on: ubuntu-latest
    steps:
      - name: Release Deleted Message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            A Release version of ${{ github.repository }} has been deleted!

            **Release Description:**
            ```
            ${{ github.event.release.body }}
            ```
