name: Send Release Messages

on:
  release:
    types: [published]

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            A new ${{ github.event.release.prerelease == true && 'pre-' || '' }}release version of ${{ github.repository }} has been created!

            **Release Description:**
            ```
            ${{ github.event.release.body }}
            ```

            Check it out at: ${{ github.event.release.html_url }}
