name: Discord Notification on Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  update_pre_release:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-Release Update Message
        if: github.event.action == 'released' && github.event.release.prerelease == true && contains(github.event.release.tag_name, 'latest')
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            A new pre-release version of ${{ github.repository }} has been created!

            **Release Description:**
            ```
            ${{ github.event.release.body }}
            ```

            Check it out at: ${{ github.event.release.html_url }}
  send_discord_message:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-release Message
        if: github.event.action == 'released' && github.event.release.release == true
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            A new pre-release version of ${{ github.repository }} has been created!

            **Release Description:**
            ```
            ${{ github.event.release.body }}
            ```

            Check it out at: ${{ github.event.release.html_url }}
